"""initial schema

Revision ID: 5fe73777a71e
Revises: 
Create Date: 2026-07-08 15:56:15.425195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fe73777a71e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_nodes_name'), 'knowledge_nodes', ['name'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_subject'), 'knowledge_nodes', ['subject'], unique=False)
    op.create_table('learning_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_routes_status'), 'learning_routes', ['status'], unique=False)
    op.create_index(op.f('ix_learning_routes_user_id'), 'learning_routes', ['user_id'], unique=False)
    op.create_table('memory_full',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.String(length=30), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_records', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_full_memory_type'), 'memory_full', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memory_full_user_id'), 'memory_full', ['user_id'], unique=False)
    op.create_table('memory_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.String(length=30), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=1024), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('full_memory_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_index_memory_type'), 'memory_index', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memory_index_topic'), 'memory_index', ['topic'], unique=False)
    op.create_index(op.f('ix_memory_index_user_id'), 'memory_index', ['user_id'], unique=False)
    op.create_table('personal_habit_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('active_time_slot', sa.String(length=20), nullable=True),
    sa.Column('content_preference', sa.String(length=20), nullable=True),
    sa.Column('avg_session_minutes', sa.Integer(), nullable=True),
    sa.Column('detail_preference', sa.String(length=20), nullable=False),
    sa.Column('weak_node_names', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('summary_cache', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cognitive_style', sa.String(length=20), nullable=False),
    sa.Column('preferred_study_time', sa.String(length=20), nullable=True),
    sa.Column('avg_session_duration', sa.Interval(), nullable=True),
    sa.Column('total_study_hours', sa.Float(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=1024), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_node_id'), 'document_chunks', ['node_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_source_type'), 'document_chunks', ['source_type'], unique=False)
    op.create_index(op.f('ix_document_chunks_subject'), 'document_chunks', ['subject'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_edges_relation_type'), 'knowledge_edges', ['relation_type'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_source_id'), 'knowledge_edges', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_target_id'), 'knowledge_edges', ['target_id'], unique=False)
    op.create_table('learning_route_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prerequisites', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['learning_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_route_steps_route_id'), 'learning_route_steps', ['route_id'], unique=False)
    op.create_index(op.f('ix_learning_route_steps_step_order'), 'learning_route_steps', ['step_order'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['learning_routes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_parent_id'), 'notes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_notes_route_id'), 'notes', ['route_id'], unique=False)
    op.create_index(op.f('ix_notes_subject'), 'notes', ['subject'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('review_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('review_type', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_plans_scheduled_at'), 'review_plans', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_review_plans_status'), 'review_plans', ['status'], unique=False)
    op.create_index(op.f('ix_review_plans_user_id'), 'review_plans', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('user_knowledge_mastery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'node_id')
    )
    op.create_index(op.f('ix_user_knowledge_mastery_next_review_at'), 'user_knowledge_mastery', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_user_knowledge_mastery_user_id'), 'user_knowledge_mastery', ['user_id'], unique=False)
    op.create_table('learning_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['learning_routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['step_id'], ['learning_route_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_records_activity_type'), 'learning_records', ['activity_type'], unique=False)
    op.create_index(op.f('ix_learning_records_started_at'), 'learning_records', ['started_at'], unique=False)
    op.create_index(op.f('ix_learning_records_user_id'), 'learning_records', ['user_id'], unique=False)
    op.create_table('lectures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_urls', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['learning_routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['step_id'], ['learning_route_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lectures_node_id'), 'lectures', ['node_id'], unique=False)
    op.create_index(op.f('ix_lectures_route_id'), 'lectures', ['route_id'], unique=False)
    op.create_index(op.f('ix_lectures_user_id'), 'lectures', ['user_id'], unique=False)
    op.create_table('note_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_tags_note_id'), 'note_tags', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_tags_tag_id'), 'note_tags', ['tag_id'], unique=False)
    op.create_table('qa_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lecture_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_sessions_user_id'), 'qa_sessions', ['user_id'], unique=False)
    op.create_table('qa_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['qa_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_messages_session_id'), 'qa_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_messages_session_id'), table_name='qa_messages')
    op.drop_table('qa_messages')
    op.drop_index(op.f('ix_qa_sessions_user_id'), table_name='qa_sessions')
    op.drop_table('qa_sessions')
    op.drop_index(op.f('ix_note_tags_tag_id'), table_name='note_tags')
    op.drop_index(op.f('ix_note_tags_note_id'), table_name='note_tags')
    op.drop_table('note_tags')
    op.drop_index(op.f('ix_lectures_user_id'), table_name='lectures')
    op.drop_index(op.f('ix_lectures_route_id'), table_name='lectures')
    op.drop_index(op.f('ix_lectures_node_id'), table_name='lectures')
    op.drop_table('lectures')
    op.drop_index(op.f('ix_learning_records_user_id'), table_name='learning_records')
    op.drop_index(op.f('ix_learning_records_started_at'), table_name='learning_records')
    op.drop_index(op.f('ix_learning_records_activity_type'), table_name='learning_records')
    op.drop_table('learning_records')
    op.drop_index(op.f('ix_user_knowledge_mastery_user_id'), table_name='user_knowledge_mastery')
    op.drop_index(op.f('ix_user_knowledge_mastery_next_review_at'), table_name='user_knowledge_mastery')
    op.drop_table('user_knowledge_mastery')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_review_plans_user_id'), table_name='review_plans')
    op.drop_index(op.f('ix_review_plans_status'), table_name='review_plans')
    op.drop_index(op.f('ix_review_plans_scheduled_at'), table_name='review_plans')
    op.drop_table('review_plans')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_subject'), table_name='notes')
    op.drop_index(op.f('ix_notes_route_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_parent_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_learning_route_steps_step_order'), table_name='learning_route_steps')
    op.drop_index(op.f('ix_learning_route_steps_route_id'), table_name='learning_route_steps')
    op.drop_table('learning_route_steps')
    op.drop_index(op.f('ix_knowledge_edges_target_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_source_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_relation_type'), table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_index(op.f('ix_document_chunks_subject'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_source_type'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_node_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('personal_habit_profile')
    op.drop_index(op.f('ix_memory_index_user_id'), table_name='memory_index')
    op.drop_index(op.f('ix_memory_index_topic'), table_name='memory_index')
    op.drop_index(op.f('ix_memory_index_memory_type'), table_name='memory_index')
    op.drop_table('memory_index')
    op.drop_index(op.f('ix_memory_full_user_id'), table_name='memory_full')
    op.drop_index(op.f('ix_memory_full_memory_type'), table_name='memory_full')
    op.drop_table('memory_full')
    op.drop_index(op.f('ix_learning_routes_user_id'), table_name='learning_routes')
    op.drop_index(op.f('ix_learning_routes_status'), table_name='learning_routes')
    op.drop_table('learning_routes')
    op.drop_index(op.f('ix_knowledge_nodes_subject'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_name'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    # ### end Alembic commands ###
