"""add note_id to lectures

Revision ID: c0826ebcce52
Revises: ff551d88ddc7
Create Date: 2026-07-10 10:06:59.559031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = 'c0826ebcce52'
down_revision: Union[str, None] = 'ff551d88ddc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('note_id', UUID(as_uuid=True), nullable=True, comment='关联的笔记 ID（讲义生成后自动创建）'))
    op.create_index(op.f('ix_lectures_note_id'), 'lectures', ['note_id'], unique=False)
    op.create_foreign_key(None, 'lectures', 'notes', ['note_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lectures', type_='foreignkey')
    op.drop_index(op.f('ix_lectures_note_id'), table_name='lectures')
    op.drop_column('lectures', 'note_id')
    # ### end Alembic commands ###
